versio: '3.8'           #La version de docker-compose, pero ya esta deprecada

services:

  web:                    #Servicio 1/ contenedor 1
    image: nginx:latest
    ports: 
     - "80:80"
    volumes:
     - ./web:/usr/share/nginx/html # volumen que usa binding , es decir es un volumen local que esta enlazado al destino. 
                                   # esto por que se muestra con  ./ que indica una ruta del host.
    enviroment:         #Variables de entorno
     - NGINX_HOST=example.com
     - NGINX_PORT=80

  proxy:                #Servicio 2 / contenedor 2
    build: ./proxy      #Se construye la imagen desde local
    ports:
      - "8080:80"
    networks:
      - red_balance
    depends_on:
      - sitio1
      - sitio2
      - sitio3
  sitio1:
    build: ./sitio1
    networks:
      - red_balance
    volumes:
      - db_data:/var/lib/postgresql/data  #volumen administrado por docker 
  sitio2:
    build: ./sitio2
    networks:
     - red_balance
  
  sitio3:
    build: ./sitio3
    networks:
      - red_balance

networks:
  red_balance:
    diver: bridge

volumes:
  db_data: