name: CI/CD Pipeline
on: 
  push:
    branches:  [ "main" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps: 
    -  name: Check out the repo
       uses: actions/checkout@v3
    -  name: Login to docker hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME}}
         password: ${{ secrets.DOCKERHUB_TOKEN}}
    -  name: Build docker image
       run: |
         docker build --platform linux --tag luiscvj/luissitioweb:latest -f CI/Dockerfile .
    -  name: Publish docker image
       run: |
         docker puch luiscvj/luissitioweb:latest

    
